#!/bin/bash

#Gather the variables

#Get docroot
echo "";
echo "What is the base Document root where all vhosts are found?";
read DOCROOT;

WP_CUR_VERSION="$(curl -s https://wordpress.org/download/ | grep "The latest stable release of WordPress" | awk '{print $9}' | cut -d \) -f 1)";
JOOMLA_CUR_VERSION="$(curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30" -s https://www.joomla.org/download.html | grep "Download Joomla " | awk '{print $10}' | cut -d \< -f 1)";
DRUPAL_CUR_VERSION="$(curl -s https://www.drupal.org/download | grep "<span>Download Drupal" | awk '{print $7}' | cut -d \< -f 1)";

echo "";
echo "Wordpress current version:  $WP_CUR_VERSION";
echo "Joomla current version:     $JOOMLA_CUR_VERSION";
echo "Druapl current version:     $DRUPAL_CUR_VERSION";

#check for installs

echo "";
echo "Looking for outdated Wordpress installs in $DOCROOT...";
WPCHECK=$(find $DOCROOT -type f -iwholename "*/wp-includes/version.php" -exec grep -H "\$wp_version =" {} \;);
find $DOCROOT -type f -iwholename "*/wp-includes/version.php" -exec grep -H "\$wp_version =" {} \; | grep -v $WP_CUR_VERSION
if [ -z "${WPCHECK}" ]; then
    echo "None found"
fi

echo "";
echo "Looking for outdated Joomla installs in $DOCROOT...";
JOOMLACHECK=$(find $DOCROOT -type f \( -iwholename '*/libraries/joomla/version.php' -o -iwholename '*/libraries/cms/version.php' -o -iwholename '*/libraries/cms/version/version.php' \) -print0 -exec perl -e 'while (<>) { $release = $1 if m/ \$RELEASE\s+= .([\d.]+).;/; $dev = $1 if m/ \$DEV_LEVEL\s+= .(\d+).;/; } print qq( = $release.$dev\n);' {} \;);
find $DOCROOT -type f \( -iwholename '*/libraries/joomla/version.php' -o -iwholename '*/libraries/cms/version.php' -o -iwholename '*/libraries/cms/version/version.php' \) -print0 -exec perl -e 'while (<>) { $release = $1 if m/ \$RELEASE\s+= .([\d.]+).;/; $dev = $1 if m/ \$DEV_LEVEL\s+= .(\d+).;/; } print qq( = $release.$dev\n);' {} \; | grep -v $JOOMLA_CUR_VERSION
if [ -z "${JOOMLACHECK}" ]; then
    echo "None found"
fi

echo "";
echo "Looking for outdated Drupal installs in $DOCROOT...";
DRUPALCHECK=$(find $DOCROOT -type f -iwholename "*/modules/system/system.info" -exec grep -H "version = \"" {} \;);
find $DOCROOT -type f -iwholename "*/modules/system/system.info" -exec grep -H "version = \"" {} \; | grep -v $DRUPAL_CUR_VERSION
if [ -z "${DRUPALCHECK}" ]; then
    echo "None found"
fi

echo "";
